### ISSUE TITLE
Bevölkerungsdaten

### ISSUE THREAD

**Issue by tobias-vetterle** [tobias-vetterle/mikrokosmos#3]
Werden nur für die Berechnung der SGB-II-Quote (LB-Anteil an Bevölkerung) benötigt; ELB-Quoten (Ausbildung, Schulabschluss) sind nur auf „arbeitssuchende ELB“ beziehbar, daher keine Berechnung von Quoten mit Bevölkerungsdaten à AF versucht, das in der Syntax umzusetzen und kontaktiert ggf. TV für weitere Hilfe

**Comment by foerster87** [comment]
Mit V 1.2 behoben
