### ISSUE TITLE
Gesamt-Quoten

### ISSUE THREAD

**Issue by tobias-vetterle** [tobias-vetterle/mikrokosmos#5]
Werden bislang nicht erstellt (z. B. SGB-II-Quote gesamt in einer Kommune); à AH prüft, wie dies direkt in Tableau umzusetzen ist; ansonsten Anpassung der Syntax nötig

**Comment by foerster87** [comment]
Sollte vermutlich doch in python erstellt werden, um Jenks-Natural-breaks-Methode umsetzen zu können (funktioniert nicht bei zu großen Datensätzen).

**Comment by tobias-vetterle** [comment]
Hat auch so geklappt, kann also wie geplant in Tableau erfolgen (wenn sonst nichts dagegen spricht)
