### ISSUE TITLE
Überlegungen zum Ausschluss von Fällen/Gemeinden

### ISSUE THREAD

**Issue by foerster87** [tobias-vetterle/mikrokosmos#7]
- mit dem Ausschluss von Fällen <100 der jeweiligen Bezugsgröße (arbeitss. ELB bzw. Bevölkerung) verliert man sehr viele Zeilen in den jeweiligen Dataframes
- Klärung erforderlich, welche Bezugsgröße tatsächlich >100 sein sollte (nur Bevölkerung oder immer der jeweilige Nenner)
- Test verschiedener Varianten steht noch aus (z.B. nur Darstellung der generalisierten SGB-2-Quote auf Gemeindeebene für Gemeinden ü100 Einwohner)
- nach Möglichkeit im Notebook festhalten: Mit welchen Sub-Datensätzen (LB und ELB) werden wie viele Gemeinden in welchem Jahr noch abgedeckt

**Comment by tobias-vetterle** [comment]
erstmal gelöst, indem auf Bezugsgröße über 20 bei den Altersgruppen in der SGB-II-Quote gefiltert wurde
